config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cablecars
  resources :telepheriques
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cable_car.rb
class CableCar < ApplicationRecord
  belongs_to :user
  has_many_attached :photos
end

app/models/telepherique.rb
class Telepherique < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cable_cars, dependent: :destroy
  has_many :telepheriques, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/cablecars_controller.rb
class CablecarsController < ApplicationController
  def index
    @cablecars = CableCar.all
  end

  def show
    @cablecar = CableCar.find(params[:id])
  end

  def new
    @cablecar = CableCar.new
    @user = current_user
    @cablecar.user = @user
  end

  def create
    @cablecar = CableCar.new(cablecar_params)
    @user = current_user
    @cablecar.user = @user

    if @cablecar.save
      flash[:notice] = "Your cablecar was successfully saved"
      redirect_to cablecar_path(@cablecar)
    else
      flash[:notice] = "Your cablecar was not saved"
      render :new
    end
  end

  private

  def cablecar_params
    params.require(:cablecar).permit(
      :name,
      :seats,
      :price,
      :city,
      :travel_length,
      :travel_speed,
      :travel_time,
      :upper_terminal,
      :lower_terminal,
      :photos
    )
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/telepheriques_controller.rb
class TelepheriquesController < ApplicationController

  def index
    @telepheriques = Telepherique.all
  end

  def show
    @telepherique = Telepherique.find(params[:id])
  end

  def new
    @telepherique = Telepherique.new
    @user = current_user
    @telepherique.user = @user
  end

  def create
    @telepherique = Telepherique.new(telepherique_params)
    @user = current_user
    @telepherique.user = @user

    if @telepherique.save
      flash[:notice] = "Your telepherique was successfully saved"
      redirect_to telepherique_path(@telepherique)
    else
      flash[:notice] = "Your telepherique was not saved"
      render :new
    end
  end

  private

  def telepherique_params
    params.require(:telepherique).permit(
      :localisation,
      :seats,
      :photos
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cablecars/index.html.erb
<p>hello</p>
<%= link_to "new cablecar", new_cablecar_path %>

app/views/cablecars/new.html.erb
<div class="container">
  <div class="form-box">
    <%= simple_form_for @cablecar do |f| %>
      <%= f.input :name %>
      <%= f.input :seats %>
      <%= f.input :price %>
      <%= f.input :city %>
      <%= f.input :travel_length %>
      <%= f.input :travel_time %>
      <%= f.input :travel_speed %>
      <%= f.input :upper_terminal %>
      <%= f.input :lower_terminal %>
      <%= f.input :photos %>
      <%= f.submit "Confirm", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CableCarMaker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>


<% if current_user %>
  <%= "Welcome to cable car maker [Known user]!"  %>
  <% else %>
  <%= "Welcome to cable car maker Visitor!" %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/telepheriques/index.html.erb
<p>Voici nos téléphériques</p>
<%= link_to "Ajouter un telepherique", new_telepherique_path %>

<%= cl_image_tag("pic1_rptarm", width: 400, height: 300, crop: :fill) %>

<div class="index-container">

  <% @telepheriques.each do |telepherique|%>
    <%= link_to telepherique_path(telepherique) do %>
      <div class="card" style="width: 18rem;">
        <%= cl_image_tag(telepherique.photo.key, width: 400, height: 300, crop: :fill, class:"card-img-top") %>
        <div class="card-body">
          <h5 class="card-title"> <%= telepherique.localisation %></h5>

          <div class="car-practical-info">

            <p class="card-text"><%= image_tag "location-pin" , class:"pin-icon"%><%= telepherique.localisation  %> </p>
            <p class="card-text"> <%= telepherique.price %> € / pers. </p>
          </div>

        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/telepheriques/new.html.erb
<div class="container">
  <div class="form-box">
    <%= simple_form_for @telepherique do |f| %>
      <%= f.input :name, label: "Nom" %>
      <%= f.input :localisation, label: "Ville" %>
      <%= f.input :travel_length, label: "Longueur (en m)" %>
      <%= f.input :travel_speed, label: "Vitesse (m/seconde)" %>
      <%= f.input :travel_time, label: "Durée du trajet" %>
      <%= f.input :lower_terminal, label: "Altitude départ"  %>
      <%= f.input :upper_terminal, label: "Altitude arrivée" %>
      <%= f.input :seats, label: "Capacité des cabines" %>
      <%= f.input :photo, as: :file %>
      <%= f.submit "Confirm", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/telepheriques/show.html.erb
<%= @telepherique.localisation %>
<%= @telepherique.seats %>
<%= @telepherique.photo %>

<div class="container">
  <div class="show-header">
    <h2> Nom du téléphérique </h2>
    <%= link_to "Retour aux telepheriques", telepheriques_path, class: "btn btn-flat" %>
  </div>

  <div class="show-top-info">
    <%= cl_image_tag(@telepherique.photo.key, width: 400, height: 300, crop: :fill) %>

    <div class="show-info-box">
      <h4> <%= image_tag "location-pin", class:"pin-icon"%><%= @telepherique.localisation %> </h3>
      <h4> Contact email : <%= @telepherique.user.email %></h4>
    </div>
  </div>
</div>